// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl24JlmS_mLiOXH6yZy_875yKKBy_9NwY',
    appId: '1:67443071179:web:744ade47e8bb57099ce34e',
    messagingSenderId: '67443071179',
    projectId: 'file-64867',
    authDomain: 'file-64867.firebaseapp.com',
    storageBucket: 'file-64867.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJti_iVlsyq2FToyyW5BtnB5IxcXSGTC8',
    appId: '1:67443071179:android:a92b6c05fcabd9199ce34e',
    messagingSenderId: '67443071179',
    projectId: 'file-64867',
    storageBucket: 'file-64867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIxFLRAjo6m59egiv_ATT4cQF4v1MV8e8',
    appId: '1:67443071179:ios:1ed30391352936379ce34e',
    messagingSenderId: '67443071179',
    projectId: 'file-64867',
    storageBucket: 'file-64867.appspot.com',
    iosClientId: '67443071179-14ilgu3vaijoic6dgure130fes8g7189.apps.googleusercontent.com',
    iosBundleId: 'com.example.toFile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIxFLRAjo6m59egiv_ATT4cQF4v1MV8e8',
    appId: '1:67443071179:ios:1ed30391352936379ce34e',
    messagingSenderId: '67443071179',
    projectId: 'file-64867',
    storageBucket: 'file-64867.appspot.com',
    iosClientId: '67443071179-14ilgu3vaijoic6dgure130fes8g7189.apps.googleusercontent.com',
    iosBundleId: 'com.example.toFile',
  );
}
